package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentAllPropertiesEquals(Content expected, Content actual) {
        assertContentAutoGeneratedPropertiesEquals(expected, actual);
        assertContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentAllUpdatablePropertiesEquals(Content expected, Content actual) {
        assertContentUpdatableFieldsEquals(expected, actual);
        assertContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentAutoGeneratedPropertiesEquals(Content expected, Content actual) {
        assertThat(expected)
            .as("Verify Content auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentUpdatableFieldsEquals(Content expected, Content actual) {
        assertThat(expected)
            .as("Verify Content relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContentUpdatableRelationshipsEquals(Content expected, Content actual) {
        // empty method
    }
}
